### ISSUE TITLE
Some icons on Thunar taskbar are not working with Viola-Dark-Global-6 theme

### ISSUE THREAD

**Issue by MasterTJ123** [L4ki/Viola-Plasma-Themes#1]
I'm having a problem on Thunar when using Viola-Dark-Global-6 theme on my kde. For some reason, the "go to the previous visited folder", "go to next visited folder" and "open the parent folder" icons don't appear. They are a blank/white square on my environment. Anything I could do? Could you fix this somehow? Works fine with other themes.

![image](https://github.com/user-attachments/assets/3f5ea6dc-fab8-4028-b3db-81fe8060da66)

**Comment by L4ki** [comment]
Hi MasterTJ123,

I'll see what the problem is, so I'll get back to you.
Thanks for the information.

**Comment by L4ki** [comment]
Hi MasterTJ123, 

I did some changes in icons themes. I installed "Thunar" and it looks like this: https://postimg.cc/3yGYbVH9

Update the icons will announce tonight around 10pm. It will be about 4pm in Brazil.

P.S.

Let me know how it is with you

**Comment by L4ki** [comment]
Updated icons:

"Azure-Dark-Icons": https://www.pling.com/p/2148992/

"Azure-Glassy-Dark-Icons": https://store.kde.org/p/2154036

**Comment by MasterTJ123** [comment]
I've downloaded the updated icons from pling and installed them on kde system settings from the file, but the problem persists. I've noticed the icon for Thunar changed, now it's a white mouse. However, the task bar didn't change at all.

![image](https://github.com/user-attachments/assets/f63b05c3-e491-4c60-871e-067d5ac24bdf)

![image](https://github.com/user-attachments/assets/2ac79d75-a786-4350-82c3-0de42202d053)

**Comment by L4ki** [comment]
I don't understand, I use Plasma 6, Plasma Theme "Viola", Icons "Azure-Dark-Icons", and with me it looks like this:

https://postimg.cc/3yGYbVH9

Try to clean cache

**Comment by MasterTJ123** [comment]
Tried to clean the cache and reboot the system, but nothing happened.

**Comment by MasterTJ123** [comment]
Should I try something else? Did the changes get to kde store already?

**Comment by L4ki** [comment]
Hi MasterTJ,

What changes specifically do you mean?

**Comment by MasterTJ123** [comment]
Not sure if it works anymore. I changed my desktop environment to Cinnamon because of some problems I was facing with KDE on Arch. Later on, I'll try it again, but I think we can close this issue for now. Maybe it was some bad configuration on my system, not anything related to the theme itself.

**Comment by L4ki** [comment]
Ok, greetings
